In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.
print(np.version.version)


1.18.1


In [15]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random([2,3,5])

#4. Print a.

print(a)

[[[0.96907852 0.3538228  0.84914816 0.85026183 0.65214963]
  [0.23094774 0.92746459 0.89506519 0.69255755 0.08912812]
  [0.99432492 0.49943752 0.35691959 0.30592924 0.70215842]]

 [[0.30295773 0.75103324 0.54592462 0.96737936 0.25559923]
  [0.75636511 0.3175953  0.36654221 0.45934055 0.42664628]
  [0.63808543 0.32418507 0.09714127 0.66374657 0.33910098]]]


In [25]:
#5. Create a 5x3x2 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


b = np.array([[[1 for i in range(1,3)],
        [1 for i in range(1,3)],
        [1 for i in range(1,3)]],

       [[1 for i in range(1,3)],
        [1 for i in range(1,3)],
        [1 for i in range(1,3)]],

       [[1 for i in range(1,3)],
        [1 for i in range(1,3)],
        [1 for i in range(1,3)]],

       [[1 for i in range(1,3)],
        [1 for i in range(1,3)],
        [1 for i in range(1,3)]],

       [[1 for i in range(1,3)],
        [1 for i in range(1,3)],
        [1 for i in range(1,3)]]])

#6. Print b.

b


array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [26]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.shape == b.shape

False

In [20]:
#8. Are you able to add a and b? Why or why not?
#a+b #because they don't have the same shape
#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,3) 


In [38]:
#9. Transpose b so that it has the same structure of a 
#(i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c"
c = b.T
c.shape == a.shape


True

In [40]:
#10.Try to add a and c. Now it should work. 
#Assign the sum to varialbe "d". But why does it work now?
#i used tranpose, now, they have the same shape
d = a+c
d

array([[[1.96907852, 1.3538228 , 1.84914816, 1.85026183, 1.65214963],
        [1.23094774, 1.92746459, 1.89506519, 1.69255755, 1.08912812],
        [1.99432492, 1.49943752, 1.35691959, 1.30592924, 1.70215842]],

       [[1.30295773, 1.75103324, 1.54592462, 1.96737936, 1.25559923],
        [1.75636511, 1.3175953 , 1.36654221, 1.45934055, 1.42664628],
        [1.63808543, 1.32418507, 1.09714127, 1.66374657, 1.33910098]]])

In [44]:
#11. Print a and d. Notice the difference and relation of the two array 
#in terms of the values? Explain 
#the difference is c, by the operation of the previous cell
a

array([[[0.96907852, 0.3538228 , 0.84914816, 0.85026183, 0.65214963],
        [0.23094774, 0.92746459, 0.89506519, 0.69255755, 0.08912812],
        [0.99432492, 0.49943752, 0.35691959, 0.30592924, 0.70215842]],

       [[0.30295773, 0.75103324, 0.54592462, 0.96737936, 0.25559923],
        [0.75636511, 0.3175953 , 0.36654221, 0.45934055, 0.42664628],
        [0.63808543, 0.32418507, 0.09714127, 0.66374657, 0.33910098]]])

In [45]:
d

array([[[1.96907852, 1.3538228 , 1.84914816, 1.85026183, 1.65214963],
        [1.23094774, 1.92746459, 1.89506519, 1.69255755, 1.08912812],
        [1.99432492, 1.49943752, 1.35691959, 1.30592924, 1.70215842]],

       [[1.30295773, 1.75103324, 1.54592462, 1.96737936, 1.25559923],
        [1.75636511, 1.3175953 , 1.36654221, 1.45934055, 1.42664628],
        [1.63808543, 1.32418507, 1.09714127, 1.66374657, 1.33910098]]])

In [46]:
#12. Multiply a and c. Assign the result to e.
e = a*c
e

array([[[0.96907852, 0.3538228 , 0.84914816, 0.85026183, 0.65214963],
        [0.23094774, 0.92746459, 0.89506519, 0.69255755, 0.08912812],
        [0.99432492, 0.49943752, 0.35691959, 0.30592924, 0.70215842]],

       [[0.30295773, 0.75103324, 0.54592462, 0.96737936, 0.25559923],
        [0.75636511, 0.3175953 , 0.36654221, 0.45934055, 0.42664628],
        [0.63808543, 0.32418507, 0.09714127, 0.66374657, 0.33910098]]])

In [47]:
#13. Does e equal to a? Why or why not? Yes, is equal
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [52]:
#14. Identify the max, min, and mean values in d. 
#Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print (f'max:{d_max}, min:{d_min}, mean: {d_mean}')



max:1.9943249234699727, min:1.0891281182962356, mean: 1.5526678923374893


In [59]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) 
#as d using `np.empty`.
f = np.empty([2,3,5])
f.shape ==d.shape

True

In [60]:
f

array([[[1.96907852, 1.3538228 , 1.84914816, 1.85026183, 1.65214963],
        [1.23094774, 1.92746459, 1.89506519, 1.69255755, 1.08912812],
        [1.99432492, 1.49943752, 1.35691959, 1.30592924, 1.70215842]],

       [[1.30295773, 1.75103324, 1.54592462, 1.96737936, 1.25559923],
        [1.75636511, 1.3175953 , 1.36654221, 1.45934055, 1.42664628],
        [1.63808543, 1.32418507, 1.09714127, 1.66374657, 1.33910098]]])

#16. Populate the values in f. For each value in d, 
#if it's larger than d_min but smaller than d_mean, 
#assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [58]:
d.shape

(2, 3, 5)

In [77]:
f

array([[[1.96907852, 1.3538228 , 1.84914816, 1.85026183, 1.65214963],
        [1.23094774, 1.92746459, 1.89506519, 1.69255755, 1.08912812],
        [1.99432492, 1.49943752, 1.35691959, 1.30592924, 1.70215842]],

       [[1.30295773, 1.75103324, 1.54592462, 1.96737936, 1.25559923],
        [1.75636511, 1.3175953 , 1.36654221, 1.45934055, 1.42664628],
        [1.63808543, 1.32418507, 1.09714127, 1.66374657, 1.33910098]]])

In [64]:
f[0][0][1]

1.3538228031852992

In [86]:
lst = []
for w in f:
    for t in w:
        for o in t:
            lst.append(o)

    

              
    

In [87]:
lst2 = []
for i in lst:
    
    if i == d_mean:
        lst2.append(50)
    elif i == d_min:
        lst2.append(0)
    elif i == d_max:
        lst2.append(100)
    elif (i > d_min) and (i < d_mean):
        lst2.append(25)
    elif (i > d_mean) and (i < d_max):
        lst2.append(75)


In [89]:
len(lst2) == len(lst)

True

In [91]:
print(lst2)

[75, 25, 75, 75, 75, 25, 75, 75, 75, 0, 100, 25, 25, 25, 75, 25, 75, 25, 75, 25, 75, 25, 25, 25, 25, 75, 25, 25, 75, 25]


In [95]:
lista_1 = [lst2[i] for i in range(0,5)]
lista_2 = [lst2[i] for i in range(5,10)]
lista_3 = [lst2[i] for i in range(10,15)]
lista_4 = [lst2[i] for i in range(15,20)]
lista_5 = [lst2[i] for i in range(20,25)]
lista_6 = [lst2[i] for i in range(25,30)]

In [96]:
lista_1

[75, 25, 75, 75, 75]

In [99]:
lst_123 = [lista_1] + [lista_2] + [lista_3]


In [100]:
lst_123

[[75, 25, 75, 75, 75], [25, 75, 75, 75, 0], [100, 25, 25, 25, 75]]

In [101]:
lst_456 = [lista_4] + [lista_5] + [lista_6]
lst_456

[[25, 75, 25, 75, 25], [75, 25, 25, 25, 25], [75, 25, 25, 75, 25]]

In [103]:
lst_n = [lst_123] + [lst_456]
n = np.array(lst_n)
n

array([[[ 75,  25,  75,  75,  75],
        [ 25,  75,  75,  75,   0],
        [100,  25,  25,  25,  75]],

       [[ 25,  75,  25,  75,  25],
        [ 75,  25,  25,  25,  25],
        [ 75,  25,  25,  75,  25]]])

In [105]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
n.np.where(n = 0,'a',n)

SyntaxError: positional argument follows keyword argument (<ipython-input-105-421dd967e43f>, line 3)